services:
  influxdb:
    container_name: influxdb_init_local
    entrypoint: /init-influxdb.sh
    environment:
      INFLUXDB_ADMIN_ENABLED: 'true'
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: supersecretpassword
      INFLUXDB_USER: testuser
      INFLUXDB_USER_PASSWORD: supersecret
      INFLUX_DB: testdb
      TZ: Europe/Amsterdam
    image: influxdb
    ports:
      - 8086:8086/tcp
    volumes:
      - influxdb:/var/lib/influxdb:rw
version: '3.0'
volumes:
  influxdb: {}
